language: elixir

elixir:
  - 1.7
  - 1.8

otp_release:
  - 19.3
  - 20.3
  - 21.0

matrix:
  exclude:
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 20.3

env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000

before_script:
  - mix deps.get
  - nvm install 8.9 && nvm use 8.9

script:
  - mix test
  - cd ./assets && npm install && npm test
